-- weddings Table
CREATE TABLE weddings (
    weddingID VARCHAR(255) NOT NULL,
    lang ENUM('as', 'bn', 'gu', 'hi', 'kn', 'ml', 'mr', 'ne', 'or', 'pa', 'ta', 'te', 'ur', 'en') DEFAULT 'en',
    domain VARCHAR(255) NOT NULL,
    weddingName VARCHAR(255) NOT NULL,
    fromRole ENUM('bride', 'groom') NOT NULL,
    brideName VARCHAR(255) NOT NULL,
    groomName VARCHAR(255) NOT NULL,
    brideQualifications VARCHAR(255),
    groomQualifications VARCHAR(255),
    brideBio TEXT,
    groomBio TEXT,
    story JSON,
    timeline JSON,
    hosts JSON,
    invitation TEXT,
    template VARCHAR(255),
    tier ENUM('basic', 'premium', 'custom') DEFAULT 'basic',
    music VARCHAR(255),
    youtube VARCHAR(255),
    accommodation TEXT,
    travel TEXT,
    phone VARCHAR (15),
    whatsappAPIKey VARCHAR(2048),
    originalPrice FLOAT,
    finalPrice FLOAT,
    host VARCHAR(255) NOT NULL,
    partner VARCHAR(255),
    manager VARCHAR(255),
    createdAt DATETIME,
    updatedAt DATETIME,
    status ENUM('pending', 'paid', 'live', 'completed') DEFAULT 'pending',
    PRIMARY KEY (weddingID, lang)
);